In [17]:
# Step 1 - Load Data
import pandas as pd
dataset = pd.read_csv("app/iphone.csv")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 3].values

In [18]:
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ['Female', 27, 57000],
       ['Male', 19, 76000],
       ['Male', 27, 58000],
       ['Female', 27, 84000],
       ['Female', 32, 150000],
       ['Male', 25, 33000],
       ['Female', 35, 65000],
       ['Female', 26, 80000],
       ['Female', 26, 52000],
       ['Male', 20, 86000],
       ['Male', 32, 18000],
       ['Male', 18, 82000],
       ['Male', 29, 80000],
       ['Male', 47, 25000],
       ['Male', 45, 26000],
       ['Male', 46, 28000]], dtype=object)

In [19]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [20]:
# Step 2 - Convert Gender to number
from sklearn.preprocessing import LabelEncoder
labelEncoder_gender =  LabelEncoder()
X[:,0] = labelEncoder_gender.fit_transform(X[:,0])

# Optional - if you want to convert X to float data type
import numpy as np
X = np.vstack(X[:, :]).astype(np.float)

In [21]:
# Step 3 - Split Data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [22]:
# Step 4 - Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
# Step 5 - Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, solver="liblinear")
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [24]:
# Step 6 - Predict
y_pred = classifier.predict(X_test)

print("Y Test")
print(y_test)
print("Y Pred")
print(y_pred)

Y Test
[0 0 0 1 0]
Y Pred
[0 0 0 1 0]


In [25]:
# Step 7 - Confusion Matrix
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)
# precision = metrics.precision_score(y_test, y_pred, average='micro') 
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)
# recall = metrics.recall_score(y_test, y_pred, average='micro')
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

[[4 0]
 [0 1]]
Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0
